one-doc:
  hosts:
    one-doc-root-orchestrator: 
      ansible_host: 192.168.178.35
      ansible_ssh_user: alex
      ansible_ssh_pass: alex
      ansible_become_password: alex
      rootIP: 192.168.178.35
      clusterName: alex-cluster
      clusterLocation: "49.743919553632935,9.005092483911229,2000"
